export const THEMES = {
  neo_brutalism: {
    id: 'neo_brutalism',
    name: 'Neo-Brutalism (Pop Art)',
    desc: 'Kalın siyah hatlar, sert gölgeler ve canlı neon pop renkler.',
    bg: 'bg-[#fef08a]',
    textColor: 'text-black',
    panel: 'bg-white border-3 border-black shadow-[5px_5px_0px_#000] rounded-2xl',
    headerPanel: 'bg-[#ec4899] border-3 border-black shadow-[4px_4px_0px_#000] rounded-2xl text-white',
    buttonPrimary: 'bg-[#3b82f6] hover:bg-[#2563eb] text-white font-black border-2 border-black shadow-[3px_3px_0px_#000] active:translate-x-0.5 active:translate-y-0.5 active:shadow-none transition-all',
    buttonSecondary: 'bg-[#fbbf24] hover:bg-[#f59e0b] text-black font-black border-2 border-black shadow-[3px_3px_0px_#000] active:translate-x-0.5 active:translate-y-0.5 active:shadow-none transition-all',
    input: 'bg-white border-2 border-black text-black font-bold shadow-[2px_2px_0px_#000] placeholder:text-gray-500 rounded-xl',
    chatMe: 'bg-[#a7f3d0] text-black border-2 border-black font-bold shadow-[3px_3px_0px_#000] rounded-2xl rounded-tr-none',
    chatOther: 'bg-white text-black border-2 border-black font-bold shadow-[3px_3px_0px_#000] rounded-2xl rounded-tl-none',
    videoContainer: 'border-3 border-black shadow-[6px_6px_0px_#000] rounded-2xl',
    badge: 'bg-[#fbbf24] text-black font-black border-2 border-black shadow-[2px_2px_0px_#000]',
    previewAccent: 'bg-[#ec4899] border-2 border-black'
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077 HUD',
    desc: 'Neon camgöbeği ışıma, yüksek teknoloji HUD çizgileri ve karanlık estetik.',
    bg: 'bg-[#05050c]',
    textColor: 'text-cyan-300 font-mono',
    panel: 'bg-[#0a0d1a]/95 border border-cyan-500/40 shadow-[0_0_20px_rgba(6,182,212,0.2)] rounded-lg',
    headerPanel: 'bg-[#0e1222] border border-cyan-500/60 shadow-[0_0_15px_rgba(6,182,212,0.3)] rounded-lg',
    buttonPrimary: 'bg-cyan-500 hover:bg-cyan-400 text-black font-black font-mono tracking-wider shadow-[0_0_12px_#06b6d4] rounded-lg active:scale-95 transition-all',
    buttonSecondary: 'bg-[#161a30] hover:bg-[#1f2444] text-cyan-400 font-mono border border-cyan-500/50 rounded-lg transition-all',
    input: 'bg-[#060814] border border-cyan-500/50 text-cyan-200 font-mono placeholder:text-cyan-700 rounded-lg focus:border-pink-500',
    chatMe: 'bg-gradient-to-r from-cyan-950 to-blue-900 text-cyan-200 border border-cyan-400/60 shadow-[0_0_10px_rgba(6,182,212,0.2)] rounded-lg rounded-tr-none',
    chatOther: 'bg-[#120e24] text-pink-300 border border-pink-500/40 shadow-[0_0_10px_rgba(236,72,153,0.15)] rounded-lg rounded-tl-none',
    videoContainer: 'border border-cyan-500/50 shadow-[0_0_25px_rgba(6,182,212,0.25)] rounded-lg',
    badge: 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/50',
    previewAccent: 'bg-cyan-400 shadow-[0_0_10px_#06b6d4]'
  },
  retro_os: {
    id: 'retro_os',
    name: 'Retro OS (Windows 95)',
    desc: '90’lar işletim sistemi pencereleri, 3D kabartmalı gri çerçeveler.',
    bg: 'bg-[#008080]',
    textColor: 'text-black font-sans',
    panel: 'bg-[#c0c0c0] border-t-2 border-l-2 border-t-white border-l-white border-b-2 border-r-2 border-b-black border-r-black shadow-lg rounded-none',
    headerPanel: 'bg-[#000080] text-white font-bold border-t border-l border-white/50 border-b border-r border-black p-2 rounded-none',
    buttonPrimary: 'bg-[#c0c0c0] hover:bg-[#d4d0c8] text-black font-bold border-t-2 border-l-2 border-t-white border-l-white border-b-2 border-r-2 border-b-black border-r-black active:border-t-black active:border-l-black active:border-b-white active:border-r-white rounded-none',
    buttonSecondary: 'bg-[#c0c0c0] hover:bg-[#d4d0c8] text-black border-t-2 border-l-2 border-t-white border-l-white border-b-2 border-r-2 border-b-black border-r-black active:border-t-black active:border-l-black active:border-b-white active:border-r-white rounded-none',
    input: 'bg-white border-t-2 border-l-2 border-t-gray-800 border-l-gray-800 border-b-2 border-r-2 border-b-white border-r-white text-black rounded-none',
    chatMe: 'bg-[#000080] text-white border border-white/40 rounded-none shadow-sm',
    chatOther: 'bg-white text-black border-t border-l border-gray-700 border-b border-r border-gray-300 rounded-none shadow-sm',
    videoContainer: 'border-t-2 border-l-2 border-t-black border-l-black border-b-2 border-r-2 border-b-white border-r-white bg-black rounded-none',
    badge: 'bg-[#000080] text-white border border-white/30',
    previewAccent: 'bg-[#000080] border border-white'
  },
  matrix: {
    id: 'matrix',
    name: 'Matrix Hacker Terminal',
    desc: 'CRT monitör hissi, yeşil fosforlu kodlar ve saf terminal düzeni.',
    bg: 'bg-[#020703]',
    textColor: 'text-emerald-400 font-mono',
    panel: 'bg-black/90 border border-emerald-500/60 shadow-[0_0_15px_rgba(16,185,129,0.2)] rounded-none',
    headerPanel: 'bg-emerald-950/80 border border-emerald-500/80 text-emerald-300 font-mono rounded-none',
    buttonPrimary: 'bg-emerald-600 hover:bg-emerald-500 text-black font-black font-mono border border-emerald-300 tracking-wider rounded-none active:scale-95 transition-all',
    buttonSecondary: 'bg-black hover:bg-emerald-950 text-emerald-400 font-mono border border-emerald-500/60 rounded-none transition-all',
    input: 'bg-black border border-emerald-500/60 text-emerald-300 font-mono placeholder:text-emerald-800 rounded-none focus:border-emerald-300',
    chatMe: 'bg-emerald-950/90 text-emerald-200 border border-emerald-500 font-mono rounded-none',
    chatOther: 'bg-[#06140a] text-emerald-400 border border-emerald-800 font-mono rounded-none',
    videoContainer: 'border-2 border-emerald-500/70 shadow-[0_0_20px_rgba(16,185,129,0.3)] rounded-none',
    badge: 'bg-emerald-950 text-emerald-400 border border-emerald-500/60',
    previewAccent: 'bg-emerald-500 shadow-[0_0_8px_#10b981]'
  },
  vaporwave: {
    id: 'vaporwave',
    name: 'Vaporwave 80s VHS',
    desc: 'Analog kaset hissi, neon fuşya-lavanta ışıltıları ve retro-wave.',
    bg: 'bg-[#120024]',
    textColor: 'text-fuchsia-200',
    panel: 'bg-[#220442]/85 border border-fuchsia-500/40 shadow-[0_0_25px_rgba(217,70,239,0.25)] rounded-2xl backdrop-blur-md',
    headerPanel: 'bg-gradient-to-r from-fuchsia-900/90 to-purple-900/90 border border-fuchsia-500/50 rounded-2xl',
    buttonPrimary: 'bg-gradient-to-r from-fuchsia-600 to-indigo-600 hover:from-fuchsia-500 hover:to-indigo-500 text-white font-bold shadow-[0_0_15px_rgba(217,70,239,0.5)] rounded-xl transition-all',
    buttonSecondary: 'bg-[#310b5a] hover:bg-[#431078] text-fuchsia-300 border border-fuchsia-500/40 rounded-xl transition-all',
    input: 'bg-[#190230] border border-fuchsia-500/40 text-fuchsia-100 placeholder:text-fuchsia-400/40 rounded-xl focus:border-cyan-400',
    chatMe: 'bg-gradient-to-r from-fuchsia-700/90 to-pink-600/90 text-white border border-pink-300/40 rounded-2xl rounded-tr-none shadow-md',
    chatOther: 'bg-[#360961]/90 text-fuchsia-200 border border-fuchsia-500/30 rounded-2xl rounded-tl-none shadow-md',
    videoContainer: 'border-2 border-fuchsia-500/60 shadow-[0_0_30px_rgba(217,70,239,0.3)] rounded-2xl',
    badge: 'bg-fuchsia-900/60 text-fuchsia-300 border border-fuchsia-500/40',
    previewAccent: 'bg-gradient-to-r from-fuchsia-500 to-indigo-500'
  },
  frutiger_aero: {
    id: 'frutiger_aero',
    name: 'Frutiger Aero (Web 2.0)',
    desc: '2000’lerin parlak jel butonları, canlı turkuaz suları ve cam yansımaları.',
    bg: 'bg-gradient-to-br from-[#7dd3fc] via-[#38bdf8] to-[#0284c7]',
    textColor: 'text-slate-900',
    panel: 'bg-white/45 border border-white/70 shadow-[0_8px_32px_rgba(2,132,199,0.3)] rounded-3xl backdrop-blur-xl',
    headerPanel: 'bg-gradient-to-b from-white/70 to-white/30 border border-white/80 rounded-2xl shadow-sm text-slate-800',
    buttonPrimary: 'bg-gradient-to-b from-sky-400 via-blue-500 to-blue-600 hover:from-sky-300 text-white font-bold rounded-full border border-white/50 shadow-[0_4px_14px_rgba(2,132,199,0.4)] active:scale-95 transition-all',
    buttonSecondary: 'bg-white/60 hover:bg-white/80 text-slate-800 font-semibold border border-white/80 rounded-full shadow-sm transition-all',
    input: 'bg-white/70 border border-white/90 text-slate-900 placeholder:text-slate-500 rounded-full shadow-inner focus:bg-white',
    chatMe: 'bg-gradient-to-b from-sky-400 to-blue-600 text-white rounded-3xl rounded-tr-xs border border-white/40 shadow-md',
    chatOther: 'bg-white/85 text-slate-800 rounded-3xl rounded-tl-xs border border-white shadow-sm',
    videoContainer: 'border-2 border-white/70 shadow-[0_12px_36px_rgba(0,0,0,0.25)] rounded-3xl',
    badge: 'bg-white/60 text-blue-900 border border-white/80 font-bold',
    previewAccent: 'bg-gradient-to-b from-sky-400 to-blue-600'
  },
  manga: {
    id: 'manga',
    name: 'Manga Sketchbook',
    desc: 'Siyah-beyaz manga sayfaları, el çizimi mürekkep çizgileri ve çizgi roman panelleri.',
    bg: 'bg-[#faf6eb]',
    textColor: 'text-black font-sans',
    panel: 'bg-white border-2 border-dashed border-black shadow-[4px_4px_0px_#000] rounded-xl',
    headerPanel: 'bg-white border-2 border-black shadow-[3px_3px_0px_#000] rounded-xl text-black',
    buttonPrimary: 'bg-black hover:bg-neutral-800 text-white font-black border-2 border-black rounded-lg shadow-[3px_3px_0px_#888] active:translate-x-0.5 active:translate-y-0.5 active:shadow-none transition-all',
    buttonSecondary: 'bg-white hover:bg-neutral-100 text-black font-bold border-2 border-black rounded-lg shadow-[3px_3px_0px_#000] transition-all',
    input: 'bg-[#faf8f2] border-2 border-black text-black font-bold placeholder:text-gray-500 rounded-lg',
    chatMe: 'bg-black text-white border-2 border-black rounded-2xl rounded-tr-none font-bold shadow-[2px_2px_0px_#888]',
    chatOther: 'bg-white text-black border-2 border-black rounded-2xl rounded-tl-none font-bold shadow-[2px_2px_0px_#000]',
    videoContainer: 'border-3 border-black shadow-[6px_6px_0px_#000] rounded-xl',
    badge: 'bg-black text-white font-bold',
    previewAccent: 'bg-black border-2 border-dashed border-white'
  }
};